# Generated by Django 6.0.3 on 2026-03-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('launching', 'Launching'), ('navigating', 'Navigating'), ('hovering', 'Hovering'), ('dropping', 'Dropping'), ('returning', 'Returning'), ('landing', 'Landing'), ('complete', 'Complete'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='pending', max_length=16)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='api.detection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
